### ISSUE TITLE
Add extra help for create command

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-project#10]
Update the `create` command to print extra background info on where to find new Cookiecutter templates and additional install options.

> Below are initial thoughts on implementation, but review of Cliff's integration with argparse revealed a more straight-forward solution that should work across the board. See `Customizing help` details below.

~~Cleanest option would be to hook into Cliffs command-level `-h` flag and add the extra information (this approach seems like it will be necessary because simply adding an `-h` argparse option conflicts with the built-in help command).~~

~~The easier (less clean) option would be to just add a new flag that doesn't conflict, e.g. `--extra-help`.~~

## Customizing help - implementation notes

> Some details on Cliff's documentation hooks

A Cliff Command subclass creates its own argparse instance, so the standard [description and epilogue](https://docs.python.org/3.7/library/argparse.html#description) arguments are available for individual command-line flags.

For overall documentation of the command itself (e.g. the text printed out when a command is invoked with `--help` and no other flags), Cliff's [Command.get_description](https://docs.openstack.org/cliff/latest/reference/index.html#cliff.command.Command.get_description) method provides defaults for documentation and hooks for customization. The default is the first line of the Command subclass docstring (see the Cliff demo app for examples).

The formatting of help text in Cliff is controlled by the underlying [Argparse defaults](https://docs.python.org/3.7/library/argparse.html#formatter-class), which collapse newlines and tabs. In order to provide nicely formatted, multi-line help text with usage examples, we'll need to pass a different formatter to argparse to preserve custom indentation on Commands and flags. This can be done on a per-command basis. For example, for the project `create` command:

```python
# datakit_project/create.py
  class Create(CommandHelpers, Command):
~     """Create a new project
+
+     Usage:
+         A handy example of usage
+     """

      def get_parser(self, prog_name):
          parser = super(Create, self).get_parser(prog_name)
+         parser.formatter_class = argparse.RawTextHelpFormatter
          parser.add_argument(
```

The above will generate text such as below:

```bash
~/Desktop> datakit project create --help
usage: datakit project create [-h] [-t TEMPLATE] [-d] [-i]

Create a new project

Usage:
    A handy example of usage
```

> Note that we've also done some help command customization in [datakit-core](https://github.com/associatedpress/datakit-core/blob/master/datakit/help.py).

It's also possible to add text to the end of the Command's overall help message using [CommandHook.get_epilog](https://docs.openstack.org/cliff/latest/reference/index.html#cliff.hooks.CommandHook.get_epilog), though this seems geared mainly at extending the functionality of a command as opposed to merely adding documentation.

Finally, Cliff also supports [Sphinx integration](https://docs.openstack.org/cliff/latest/user/sphinxext.html) for documentation on the Command class.

**Comment by michelleminkoff** [comment]
FYI, I ran into this issue on the local AP version of datakit while setting up our new intern, Riin. I hadn't seen this discussion on GitHub (was focused on GitLab) and had no clue how to get default templates for her. Whatever solution is developed, could we make sure it's looped into the AP-specific version as well?

**Comment by zstumgoren** [comment]
Added some basic research on  documentation hooks in Cliff. The appropriate strategy will vary by context (e.g. when documenting a command flag vs. extending docs on the command itself). Seems like we'll generally want to override the Command's help and/or customize the description/epilogue arguments on command flags.

**Comment by zstumgoren** [comment]
Updated ticket description with an important note:  Cliff appears to collapse newlines/tabs on Command class docstrings, `get_description`, and the `get_epilog` commands. This may limit our ability to provide extended, multi-line help text with usage examples. Need to look into this more...

**Comment by zstumgoren** [comment]
Updated ticket description with solution to the collapsing of newlines/tabs. TL;DR - configure each command's argparse instance with a different formatter such as [argparse.RawTextHelpFormatter](https://docs.python.org/3.7/library/argparse.html#argparse.RawTextHelpFormatter). See ticket description for more details.

**Comment by zstumgoren** [comment]
Updated help text to display more informative message. Implemented using custom argparse formatter (to retain white space) and by overriding [`Command.get_epilog`](https://docs.openstack.org/cliff/latest/reference/index.html#cliff.command.Command.get_epilog):

```
~/Desktop> datakit project create --help
usage: datakit project create [-h] [-t TEMPLATE] [-d] [-i]

Create a new project.

optional arguments:
  -h, --help            show this help message and exit
  -t TEMPLATE, --template TEMPLATE
                        Local path/Github URL for a Cookiecutter template
  -d, --make-default    Make the template the default for new projects
  -i, --no-input        Disable prompts for CLI input

To use a locally installed template:

    datakit project create --template my-awesome-cookiecutter

To install a new template, you must invoke "datakit project create" with
the local path or URL to a Cookiecutter project repo, e.g.:

    datakit project create --template /local/path/to/my-awesome-cookiecutter-template

Check out the below URLs for pre-baked templates and installation options:

  - A Pantry Full of Cookiecutters
      https://cookiecutter.readthedocs.io/en/latest/readme.html#a-pantry-full-of-cookiecutters

  - Template install docs
      https://datakit-project.readthedocs.io/en/latest/#creating-your-first-project
```
