### ISSUE TITLE
Add extra help when aws is not configured

### ISSUE THREAD

**Issue by michelleminkoff** [associatedpress/datakit-project#11]
Similar to #10, when setting up someone new on datakit commands I failed out trying to do datakit data pull, not knowing aws configure had to be run. Some help text prompting this would have saved a lot of time (and even some frustration) here as well.

**Comment by zstumgoren** [comment]
@michelleminkoff This is a good idea but appropriate locale to discuss is the [datakit-data repo](https://github.com/associatedpress/datakit-data/issues). Can you migrate this ticket there?

**Comment by zstumgoren** [comment]
Looks like you created a new ticket on datakit-data. Thanks!
