### ISSUE TITLE
Simplify namespacing for template commands?

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-project#21]
We've generally been following the `<plugin> <command>` namespacing convention on datakit's various plugins. For example, `datakit project create`.

Should we break the convention for the proposed template commands in order to spare users some typing?

For example:

* `datakit templates` lists locally installed templates
* `datakit templates update` updates one or more templates

Instead of:

* `datakit project templates`
* `datakit project templates update`

One potential downside is the possibility of a third party creating an unrelated plugin for templates that conflicts with these commands.

On a related note, while it's possible to provide both sets of commands (with and without the `project` prefix) as aliases to the same functionality, I'd prefer to pick only one to avoid cluttering up the `datakit --help` text with numerous aliases.

**Comment by zstumgoren** [comment]
@larryfenn @meghanhoyer @tthibo @michelleminkoff @myersjustinc @kastanis Howdy folks. Wondering if you can provide feedback on this question. Detailed comments are welcome, but even a simple thumbs up (or down) to indicate support for shortening the command names would to would  helpful.

**Comment by michelleminkoff** [comment]
I'm fine with being outvoted, but I would prefer NOT to shorten it, for consistency of naming and the human-readable reminder that these templates are related to the overall project, not the structure of a data or config file or something else.

**Comment by myersjustinc** [comment]
Mostly indifferent, but leaning toward what Michelle said. Call me [a -0](https://docs.djangoproject.com/en/2.2/internals/contributing/bugs-and-features/#how-we-make-decisions).

**Comment by tthibo** [comment]
I'd say this is one where the reduction in typing doesn't merit the breaking of convention. But you know me, I was always pushing for the natural language "datakit list project templates," which ended up being more trouble than it was worth.

**Comment by zstumgoren** [comment]
Ok, sounds like folks are in favor of preserving the convention. Thanks for the speedy feedback!
