### ISSUE TITLE
House/link each person's d.w. API key?

### ISSUE THREAD

**Issue by meghanhoyer** [associatedpress/datakit-project#24]
Is there a way to automatically set up dworld configs with each person’s api key so that when someone creates a project, it automatically creates the necessary datakit-dworld config file?

**Comment by zstumgoren** [comment]
I no longer have access to the datakit-dworld code base, so @myersjustinc is best equipped to answer this. But I'm guessing the dworld library code is written in such a way that it would read a user's data.world API key from a local environment variable and/or a plugin configuration file in `~/.datakit/plugins/datakit-dworld`.  The setting of the environment variable or addition of the API key to the plugin config would typically be a manual step following *pip* installation of the `datakit-dworld` library. 

It sounds like you're asking if team member API keys could be stored in a central location (or perhaps obtained programmatically from data.world via API?) and installed/configured locally when the plugin is installed? Plugins depending on third-party APIs typically require a manual workflow to obtain and install API keys, but perhaps there's something bespoke you all can come up with that is secure to automate this configuration step. 

A more generic alternative would be to update the library to warn users when the API key is not configured locally, and provide guidance on how to obtain and install the key. Still requires a manual workflow, but at least points folks in the right direction.

Anyhow, probably best for you and @myersjustinc to hash this out on the dworld project's issue tracker. Closing for now.
