### ISSUE TITLE
Modify .gitignore to properly sync empty folders

### ISSUE THREAD

**Issue by shardsofblue** [associatedpress/datakit-project#29]
For GitHub to see and sync empty folders, .gitignore must be configured to `folder/*` (as well as possessing .gitkeep files). Both `data/` and `scratch/` lines should be updated to `data/*` and `scratch/*`.

**Comment by larryfenn** [comment]
Had to adopt a slightly different approach for the nested folders but this has been changed in all the AP cookiecutters:

https://github.com/associatedpress/cookiecutter-r-project/commit/88a46209c013674325d572088641f82671a59d59

https://github.com/associatedpress/cookiecutter-python-project/commit/d6f0c2bd2c2fd3274b7322db851ab3e8d660a896

https://github.com/associatedpress/cookiecutter-generic-project/commit/e8e62cbfb856a808b633349da8dbb4eef5a7fa43
